version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
       # Grouped version updates configuration
       all-dependencies:
          patterns:
            - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/src/OrchardCore.Modules/OrchardCore.AdminDashboard"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/src/OrchardCore.Modules/OrchardCore.AdminMenu"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/src/OrchardCore.Modules/OrchardCore.Apis.GraphQL"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/src/OrchardCore.Modules/OrchardCore.Markdown"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/src/OrchardCore.Modules/OrchardCore.Media"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/src/OrchardCore.Modules/OrchardCore.Resources"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/src/OrchardCore.Modules/OrchardCore.Setup"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/src/OrchardCore.Modules/OrchardCore.Themes"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/src/OrchardCore.Modules/OrchardCore.Shortcodes"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/src/OrchardCore.Modules/OrchardCore.Workflows"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/src/OrchardCore.Themes/TheAdmin"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/src/OrchardCore.Themes/TheAgencyTheme"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/src/OrchardCore.Themes/TheTheme"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
