language: csharp
sudo: required
dist: trusty
dotnet: 1.0.0-preview2-1-003177
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1   
    - TEMP: "$TRAVIS_BUILD_DIR/.temp"
mono: none
os:
  - linux
  - osx
osx_image: xcode8.2
script:
  - dotnet restore
  - dotnet build -c Release
  - dotnet test -c Release ./test/Orchard.Tests/Orchard.Tests.csproj
