language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 1.0.3
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1   
    - TEMP: "$TRAVIS_BUILD_DIR/.temp"
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main'
      key_url: 'https://apt-mo.trafficmanager.net/keys/microsoft.asc'
    packages:
    - dotnet-dev-1.0.1
os:
  - linux
  - osx
osx_image: xcode8.2
script:
  - dotnet restore
  - dotnet build -c Release
  - dotnet test -c Release ./test/Orchard.Tests/Orchard.Tests.csproj
