image:
- Ubuntu
- Visual Studio 2017

environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOCKER_USER:
      secure: 2a9QfyDw5J1NDZD80kMwhQ==
    DOCKER_PASS:
      secure: aLjaywnziVFcRa3uZ8iMteFDjA1wp0fSaPMaBE55LO4=
    MYGET_API_KEY:
        secure: 8Fp2ETunhU6PvhlotuQXTZ7WkG1FikJ3BM7YLAZyfmbpy00knABu5yL7MhJ9uNcl
    NUGET_API_KEY:
        secure: bR0JuO8NuLOxL18tQ7ZtQXOHNHjqCJXlkUOzEyNQniptTszwYcwufYhKTyoybqei

stack: node 9, docker

# Install scripts. (runs after repo cloning)
install:

  # Download .NET Core 2.1 SDK and add to PATH
  - ps: |
      if ($isWindows)
      {
        $env:DOTNET_INSTALL_DIR = "$pwd/.build"
        New-Item -ItemType Directory -Force -Path $env:DOTNET_INSTALL_DIR
        wget "https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.ps1" -OutFile "$env:DOTNET_INSTALL_DIR/dotnet-install.ps1"
        .build/dotnet-install.ps1 -Channel 2.1.300 -SkipNonVersionedFiles -Version 2.1.300
        $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"
      }

  - sh: |
      if [ "$CI_LINUX" = "true" ]
      then
        mkdir -p ./.build
        wget -P ./.build/ "https://raw.githubusercontent.com/dotnet/cli/master/scripts/obtain/dotnet-install.sh"
        chmod +x ./dotnet-install.sh
        ./.build/dotnet-install.sh --channel 2.1.300 --skip-non-versioned-files --version 2.1.300
      fi

  # Set the BuildNumber property used in OrchardCore.Commons.props
  - ps: $env:BuildNumber= $env:APPVEYOR_BUILD_NUMBER

  - ps: $IsMasterBranch = ($env:APPVEYOR_REPO_BRANCH -eq "master" -And -not $env:APPVEYOR_PULL_REQUEST_NUMBER)
  - ps: $IsDevBranch = ($env:APPVEYOR_REPO_BRANCH -eq "dev" -And -not $env:APPVEYOR_PULL_REQUEST_NUMBER)

init:
  - git config --global core.autocrlf true

build_script:
  - dotnet --version
  - ps: if (($IsMasterBranch -eq $true) -or ($IsDevBranch -eq $true)) { dotnet pack -c Release }

  - ps: |
      if (($IsMasterBranch -eq $true) -and ($isWindows))
      {
        cd $env:APPVEYOR_BUILD_FOLDER\src\OrchardCore.Cms.Web
        dotnet publish -c Release -o $env:APPVEYOR_BUILD_FOLDER\.build\release
        cd $env:APPVEYOR_BUILD_FOLDER
        docker build -t orchardproject/orchardcore-cms-windows:latest -t orchardproject/orchardcore-cms-windows:1.0.0-beta2 .
        docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
        docker push orchardproject/orchardcore-cms-windows
      }

      if (($IsDevBranch -eq $true) -and ($isWindows))
      {
        cd $env:APPVEYOR_BUILD_FOLDER\src\OrchardCore.Cms.Web
        dotnet publish -c Release -o $env:APPVEYOR_BUILD_FOLDER\.build\release
        cd $env:APPVEYOR_BUILD_FOLDER
        docker build -t orchardproject/orchardcore-cms-windows:dev .
        docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
        docker push orchardproject/orchardcore-cms-windows
      }

      if (($IsMasterBranch -eq $true) -and ($isLinux))
      {
        cd $env:APPVEYOR_BUILD_FOLDER/src/OrchardCore.Cms.Web
        dotnet publish -c Release -o $env:APPVEYOR_BUILD_FOLDER/.build/release
        cd $env:APPVEYOR_BUILD_FOLDER
        docker build -t orchardproject/orchardcore-cms-linux:latest -t orchardproject/orchardcore-cms-linux:1.0.0-beta2 .
        docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
        docker push orchardproject/orchardcore-cms-linux
      }

      if (($IsDevBranch -eq $true) -and ($isLinux))
      {
        cd $env:APPVEYOR_BUILD_FOLDER/src/OrchardCore.Cms.Web
        dotnet publish -c Release -o $env:APPVEYOR_BUILD_FOLDER/.build/release
        cd $env:APPVEYOR_BUILD_FOLDER
        docker build -t orchardproject/orchardcore-cms-linux:dev .
        docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
        docker push orchardproject/orchardcore-cms-linux
      }

test_script:
  - dotnet --version
  - node --version
  - npm --version
  - dotnet test -c Release ./test/OrchardCore.Tests/OrchardCore.Tests.csproj
  - cd ./test/Functional
  - ps: .\test-setup.ps1
  - ps: .\test-run.ps1

clone_depth: 1
test: on

artifacts:
- path: 'src/**/*.nupkg'

deploy_script:
- ps:  if (($IsMasterBranch -eq $true) -and ($isWindows)) { foreach ($artifactName in $artifacts.keys) { nuget push $artifacts[$artifactName].path $env:NUGET_API_KEY -Source https://www.nuget.org/api/v2/package } }
- ps:  if (($IsDevBranch -eq $true) -and ($isWindows)) { foreach ($artifactName in $artifacts.keys) { nuget push $artifacts[$artifactName].path $env:MYGET_API_KEY -Source https://www.myget.org/F/orchardcore-preview/api/v2/package } }
