name: UI Tests
description: Runs UI tests and publishes the failure dumps as an artifact on test failure.

inputs:
  os-name:
    description: The name of the OS used for the runner (e.g. "ubuntu-latest").
    required: true

runs:
  using: "composite"
  steps:
    - name: UI Tests
      shell: bash
      run: |
        dotnet test -c Release --no-restore --no-build ./test/OrchardCore.Tests.UI/OrchardCore.Tests.UI.csproj
    - uses: actions/upload-artifact@v2
      if: failure() && hashFiles('test/OrchardCore.Tests.UI/bin/Release/*/FailureDumps')
      with:
        name: ui-test-failure-${{ inputs.os-name }}
        path: |
          test/OrchardCore.Tests.UI/bin/Release/*/FailureDumps
    - name: MVC UI Tests
      shell: bash
      run: |
        dotnet test -c Release --no-restore --no-build ./test/OrchardCore.Tests.UI.Mvc/OrchardCore.Tests.UI.Mvc.csproj
    - uses: actions/upload-artifact@v2
      if: failure() && hashFiles('test/OrchardCore.Tests.UI.Mvc/bin/Release/*/FailureDumps')
      with:
        name: mvc-ui-test-failure-${{ inputs.os-name }}
        path: |
          test/OrchardCore.Tests.UI.Mvc/bin/Release/*/FailureDumps
