name: Community Metrics
on:
  pull_request:
    
permissions:
  issues: write
  pull-requests: read

jobs:
  generate-community-metrics:
    name: Generate Community Metrics
    runs-on: ubuntu-latest
    steps:
    - name: Close Previous Issue
      shell: pwsh
      run: |
        $issues = gh issue list --label 'community metrics' --state open --json number --jq '.[].number'
        foreach ($issue in $issues)
        {
            Write-Output "Closing issue $issue"
        }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

