name: Dev Build
on:
  push:
    paths-ignore:
      - '**/*.md'
      - 'mkdocs.yml'
      - 'src/docs/**/*'
    branches:
      - 'jptissot/actions_fix'
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  test:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.404
    - name: Set build number 
      run: echo "BuildNumber=$(( $GITHUB_RUN_NUMBER + 15471 ))" >> $GITHUB_ENV
    - name: Build
      run: |
        dotnet build --configuration Release
    - name: Unit Tests
      run: |
        dotnet test -c Release --no-restore --no-build ./test/OrchardCore.Tests/OrchardCore.Tests.csproj 
    - name: Functional Tests
      run: |
        cd test/Functional
        npm install
        npm run cms:test
        npm run mvc:test
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: Functional Test failure
        path: |
          test/Functional/cms-tests/cypress/screenshots
          src/OrchardCore.Cms.Web/App_Data/logs
    - name: Deploy preview nuget packages
      run: |
        dotnet pack -c Release --no-restore --no-build --include-symbols
    #    dotnet nuget push './src/**/*.nupkg' -k ${{secrets.CLOUDSMITH_API_KEY}} -n true -s https://nuget.cloudsmith.io/orchardcore/preview/v3/index.json --skip-duplicate
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Deploy preview docker image for linux
      run: |
        dotnet publish -c Release -o ./.build/release --no-build --no-restore
        docker build -t orchardproject/orchardcore-cms-linux:dev .
      #  docker push orchardproject/orchardcore-cms-linux
  
  deploy_docker_windows:
    needs: [test]
    runs-on: windows-latest
    name: Deploy preview docker image for windows
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.404
    - name: Dotnet Build
      run: |
        rm -rf ./src/OrchardCore.Cms.Web/App_Data
        dotnet publish -c Release -o ./.build/release
    - name: Docker build and push (dev)
      run: |
        docker build -t orchardproject/orchardcore-cms-windows:dev .
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u="${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      #  docker push orchardproject/orchardcore-cms-windows
