name: Dev deployment on cloudsmith and docker
on:
  workflow_run:
    workflows: ["Build and Test"]
jobs:
  deploy_cloudsmith:
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      BuildNumber: ${{ github.run_id }}
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.404
    - name: Build, pack and push nuget packages
      run: |
        dotnet build --configuration Release
    - name: Pack
      run: dotnet pack -c Release -o pack-output --no-build
    # - name: Publish nuget
    #   run: dotnet nuget push './pack-output/*.nupkg' -k ${{secrets.CLOUDSMITH_API_KEY}} -n true -s https://nuget.cloudsmith.io/orchardcore/preview/v3/index.json --skip-duplicate
