name: Validating Building the Documentation

on: 
  push:
    paths:
      - 'mkdocs.yml'
      - 'src/docs/**/*'
    branches: [ main ]
  pull_request:
    branches: [ main, release/** ]
    paths:
      - 'mkdocs.yml'
      - 'src/docs/**/*'

concurrency:
  group: ${{ github.head_ref || github.run_id }}-docs_validation
  cancel-in-progress: true

jobs:
  validate-building-documentation:
    name: Validating Building the Documentation
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5 
    
    - name: Install Dependencies
      run: pip install -r src/docs/requirements.txt -v

    - name: Build Documentation
      run: python -m mkdocs build --strict
