name: Unit Tests - MacOS
on:
# manual trigger
  workflow_dispatch:
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  test:
    runs-on: macos-latest
    name: Unit Tests
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: dotnet build -c Release -warnaserror /p:TreatWarningsAsErrors=true /p:RunAnalyzers=true
    - name: Run Test
      run: dotnet test -c Release --no-restore --no-build ./test/OrchardCore.Tests/OrchardCore.Tests.csproj
      env: 
        OrchardCore__OrchardCore_YesSql__EnableThreadSafetyChecks: true
