name: PR - CI
on: 
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'mkdocs.yml'
      - 'src/docs/**/*'
    branches:
      - dev
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOCKER_BUILDKIT: 1
jobs:
  build_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: Build & Test
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core on ${{ matrix.os }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.404
    - name: Deploy preview docker image for linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        rm -rf ./src/OrchardCore.Cms.Web/App_Data
        dotnet publish -c Release -o ./.build/release --no-build --no-restore
        docker build -f Dockerfile-CI -t orchardproject/orchardcore-cms-linux:dev .
    - name: Deploy preview docker image for windows
      if: matrix.os == 'windows-latest'
      run: |
        Get-ChildItem ./src/OrchardCore.Cms.Web/App_Data -Recurse | Remove-Item
        dotnet publish -c Release -o ./.build/release --no-build --no-restore
        docker build -f Dockerfile-CI -t orchardproject/orchardcore-cms-windows:dev .
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u="${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
  