name: PR - CI
on: 
  pull_request:
    branches: [ main, release/** ]
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  build_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    name: Build & Test
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "15"
    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: |
        dotnet build --configuration Release --framework net6.0
    #- name: Unit Tests
    #  run: |
    #    dotnet test -c Release --no-restore --no-build ./test/OrchardCore.Tests/OrchardCore.Tests.csproj
    #- name: MVC UI Tests
    #  uses: Lombiq/GitHub-Actions/.github/actions/test-dotnet@issue/OSOE-424
    #  with:
    #    build-directory: test/OrchardCore.Tests.UI.Mvc
    - name: Set up Azurite
      uses: Lombiq/GitHub-Actions/.github/actions/setup-azurite@issue/OSOE-424
      with:
        location: test/OrchardCore.Tests.UI
    #- name: CMS UI Tests - SQLite
    #  uses: Lombiq/GitHub-Actions/.github/actions/test-dotnet@issue/OSOE-424
    #  with:
    #    build-directory: test/OrchardCore.Tests.UI
    #- name: Set up SQL Server
    #  uses: Lombiq/GitHub-Actions/.github/actions/setup-sql-server@issue/OSOE-424
    #- name: CMS UI Tests - SQL Server
    #  uses: Lombiq/GitHub-Actions/.github/actions/test-dotnet@issue/OSOE-424
    #  env:
    #    OrchardCore__UITestingCIDatabaseProvider: "SqlServer"
    #  with:
    #    build-directory: test/OrchardCore.Tests.UI
    - name: Start PostgreSQL
      # v1 branch as of 06.11.2022.
      uses: ankane/setup-postgres@fb3b63234a45536dde68bae3f8cf1b6dbbc281cb
      with:
        database: postgres
    - name: CMS UI Tests - PostgreSQL
      uses: Lombiq/GitHub-Actions/.github/actions/test-dotnet@issue/OSOE-424
      env:
        OrchardCore__UITestingCIDatabaseProvider: "Postgres"
      with:
        build-directory: test/OrchardCore.Tests.UI
    # MariaDB is an open-source drop-in replacement of MySQL, so we can use it instead.
    #- name: Set up MariaDB
    #  # v1 branch as of 06.11.2022.
    #  uses: ankane/setup-mariadb@81fcdda23edba40ba0762fb8fff403e320a46f76
    #  with:
    #    database: mariadb
    #- name: CMS UI Tests - MySql
    #  uses: Lombiq/GitHub-Actions/.github/actions/test-dotnet@issue/OSOE-424
    #  env:
    #    OrchardCore__UITestingCIDatabaseProvider: "MySql"
    #  with:
    #    build-directory: test/OrchardCore.Tests.UI
