name: PR - CI
on: 
  pull_request:
    branches: [ main, release/** ]
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  build_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: Build & Test
    steps:
    - name: Test execution debug
      uses: Lombiq/GitHub-Actions/.github/actions/test-dotnet@issue/OSOE-424
      env:
        OrchardCore__ConnectionString: "User ID=postgres;Password=postgres;Host=localhost;Port=5432;Database=postgres;"
        OrchardCore__DatabaseProvider: "Postgres"
      with:
        build-directory: test/OrchardCore.Tests.UI
