name: PR - CI
on: 
  pull_request:
    branches: [ main, release/** ]
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  windows-latest:
    name: windows-latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache .nuke/temp, ~/.nuget/packages
        uses: actions/cache@v2
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('global.json', 'src/**/*.csproj', 'src/**/package.json') }}
      - name: Run './build.cmd Compile Test Pack'
        run: ./build.cmd Compile Test Pack
      - uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: artifacts
  ubuntu-latest:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache .nuke/temp, ~/.nuget/packages
        uses: actions/cache@v2
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('global.json', 'src/**/*.csproj', 'src/**/package.json') }}
      - name: Run './build.cmd Compile Test Pack'
        run: ./build.cmd Compile Test Pack
      - uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: artifacts
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: functional-test-failure
          path: |
            test/OrchardCore.Tests.Functional/cms-tests/cypress/screenshots
            src/OrchardCore.Cms.Web/App_Data/logs

