name: PR - CI
on: 
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'mkdocs.yml'
      - 'src/docs/**/*'
    branches:
      - dev
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  build_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: Build & Test
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core on ${{ matrix.os }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.404
    - name: Build
      run: |
        dotnet build --configuration Release
    - name: Deploy preview docker image for linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        docker build -t orchardproject/orchardcore-cms-linux:dev .
    - name: Deploy preview docker image for windows
      if: matrix.os == 'windows-latest'
      run: |
        docker build -t orchardproject/orchardcore-cms-windows:dev .