name: Preview - CI
on:
  workflow_dispatch:
  schedule:
    # 4:19 AM UTC every day. A random time to avoid peak times of GitHub Actions.
    - cron: '19 4 * * *'
  pull_request:
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  test:
    runs-on: ubuntu-latest
    name: Build, Test, Deploy
    steps:
    - uses: actions/checkout@v4
      with:
        # Necessary to count commits below. We assume that no more than 50 commits are pushed in a day to main.
        fetch-depth: 50
    - name: Check for new commits
      id: check-commits
      shell: pwsh
      run: |
        $commitCount = (git log --oneline --since '24 hours ago' | Measure-Object -Line).Lines
        Write-Output "Count of new commits found in the last 24 hours: $commitCount."
        "commit-count=$commitCount" >> $Env:GITHUB_OUTPUT
    - uses: actions/setup-node@v3
      if: steps.check-commits.outputs.commit-count > 0
      with:
        node-version: "15"
    - uses: actions/setup-dotnet@v3
      if: steps.check-commits.outputs.commit-count > 0
      with:
        dotnet-version: '8.0.x'
    - name: Set build number
      if: steps.check-commits.outputs.commit-count > 0
      run: echo "BuildNumber=$(( $GITHUB_RUN_NUMBER + 16368 ))" >> $GITHUB_ENV
    - name: Build
      if: steps.check-commits.outputs.commit-count > 0
      run: |
        dotnet build -c Release
    - name: Unit Tests
      if: steps.check-commits.outputs.commit-count > 0
      run: |
        dotnet test -c Release --no-build ./test/OrchardCore.Tests/OrchardCore.Tests.csproj 
    - name: Functional Tests
      if: steps.check-commits.outputs.commit-count > 0
      run: |
        cd test/OrchardCore.Tests.Functional
        npm install
        npm run cms:test
        npm run mvc:test
    - uses: actions/upload-artifact@v2
      with:
        name: Functional Test failure
        path: |
          test/OrchardCore.Tests.Functional/cms-tests/cypress/screenshots
          src/OrchardCore.Cms.Web/App_Data_Tests/logs
