name: Preview - CI
on:
  pull_request:
  workflow_dispatch:
  schedule:
    # 4:19 AM UTC every day. A random time to avoid peak times of GitHub Actions.
    - cron: '19 4 * * *'
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  test:
    runs-on: ubuntu-latest
    name: Build, Test, Deploy
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      if: steps.check-publish.outputs.should-publish == 'true'
      with:
        node-version: "15"
    - uses: actions/setup-dotnet@v4
      if: steps.check-publish.outputs.should-publish == 'true'
      with:
        dotnet-version: '8.0.x'
    - name: Set build number
      if: steps.check-publish.outputs.should-publish == 'true'
      run: echo "BuildNumber=$(( $GITHUB_RUN_NUMBER + 16368 ))" >> $GITHUB_ENV
    - name: Build
      if: steps.check-publish.outputs.should-publish == 'true'
      run: |
        dotnet build -c Release
    - name: Unit Tests
      if: steps.check-publish.outputs.should-publish == 'true'
      run: |
        dotnet test -c Release --no-build ./test/OrchardCore.Tests/OrchardCore.Tests.csproj 
    - name: Functional Tests
      if: steps.check-publish.outputs.should-publish == 'true'
      run: |
        cd test/OrchardCore.Tests.Functional
        npm install
        npm run cms:test
        npm run mvc:test
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: Functional Test failure
        path: |
          test/OrchardCore.Tests.Functional/cms-tests/cypress/screenshots
          src/OrchardCore.Cms.Web/App_Data_Tests/logs
    - name: Set up Docker Buildx
      if: steps.check-publish.outputs.should-publish == 'true'
      uses: docker/setup-buildx-action@v3
    - name: Login to DockerHub
      if: steps.check-publish.outputs.should-publish == 'true'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
