name: Preview - CI
on:
  workflow_dispatch:
  schedule:
    # 4:19 AM UTC every day. A random time to avoid peak times of GitHub Actions.
    - cron: '19 4 * * *'
  pull_request:
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  test:
    runs-on: ubuntu-latest
    name: Build, Test, Deploy
    steps:
    - uses: actions/checkout@v4
      with:
        # Necessary to count commits below. We assume that no more than 50 commits are pushed in a day to main.
        fetch-depth: 50
    - name: Check for new commits
      id: check-commits
      shell: pwsh
      run: |
        $commitCount = (git log --oneline --since '24 hours ago' | Measure-Object -Line).Lines
        Write-Output "Count of new commits found in the last 24 hours: $commitCount."
        "commit-count=$commitCount" >> $Env:GITHUB_OUTPUT
    - uses: actions/setup-node@v3
      if: steps.check-commits.outputs.commit-count > 0
      with:
        node-version: "15"
