name: Workflow1
on: 
 # pull_request:
  push:
    branches:
   #   - 'dev'
    #  - 'master'
      - 'jptissot/github_actions'
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
